### ISSUE TITLE
Allow special characters in abbreviations

### ISSUE THREAD

**Issue by daobrien** [theacrobot/AcroBot#23]
e.g., allow for xml:tm (XML-based Text Memory)
@ggainey ?

**Comment by thescouser89** [comment]
Hi David! I think this is due to the regex here: https://github.com/theacrobot/AcroBot/blob/master/AcroBot.rb#L98

You see that only words, `-' and `_` are allowed in the abbreviation. We could relax those constraints a little bit to support 'D+I' and 'D&I'

```
irb(main):003:0> "!aha=hello here now".match(/^!([\w\-\_]+)\=(.+)/)
=> #<MatchData "!aha=hello here now" 1:"aha" 2:"hello here now">
irb(main):004:0> "!aha+B=hello here now".match(/^!([\w\-\_]+)\=(.+)/)
=> nil
irb(main):005:0> "!aha+B=hello here now".match(/^!([\w\-\_\+\&]+)\=(.+)/)
=> #<MatchData "!aha+B=hello here now" 1:"aha+B" 2:"hello here now">
irb(main):006:0> 
```
